In [7]:
import numpy as np
from sklearn.model_selection import KFold

rng = np.random.RandomState(123)
y = np.array([0,0,0,0,0,1,1,1,1,1])
X = rng.random_sample((y.shape[0], 4)) # example inputs, 10 x 4 dimensional datasets

cv = KFold(n_splits=5)

for k in cv.split(X, y):
    print(k)

X


(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1]))
(array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3]))
(array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5]))
(array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7]))
(array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))


array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426, 0.73799541],
       [0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866, 0.22826323],
       [0.29371405, 0.63097612, 0.09210494, 0.43370117],
       [0.43086276, 0.4936851 , 0.42583029, 0.31226122],
       [0.42635131, 0.89338916, 0.94416002, 0.50183668]])